### ISSUE TITLE
dark mode not working

### ISSUE THREAD

**Issue by joamatab** [executablebooks/myst-theme#303] opened 2023-12-09 20:38 UTC
### Describe the bug

**context**
When I enable dark mode
https://joamatab.github.io/gdsfactory

and i go to another tab on the right , the dark mode disappears

**expectation**
I expect darkmode to stick as it happens with jupyterbook
https://gdsfactory.github.io/gdsfactory/notebooks/_3_vscode.html

### Reproduce the bug

build docs on CICD

https://github.com/joamatab/gdsfactory

### List your environment

```
Jupyter Book      : 0.15.1
External ToC      : 0.3.1
MyST-Parser       : 0.18.1
MyST-NB           : 0.17.2
Sphinx Book Theme : 1.0.1
Jupyter-Cache     : 0.6.1
NbClient          : 0.7.4
```

**Comment by rowanc1** [comment] 2024-03-11 13:27
Duplicate of #319 and #233. Closing this in favour of discussion in #319.

**Closed** 2024-03-11 13:31 UTC
Labels: bug
