### ISSUE TITLE
Dark mode selection does not persist during site navigation

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/myst-theme#233] opened 2023-09-11 19:05 UTC
Copied from here: https://github.com/executablebooks/mystmd/issues/585

If I activate dark mode on a page, then navigate to another page in the same MyST site, it reverts to light mode. I would expect dark mode selection to persist during site navigation.

**Comment by rowanc1** [comment] 2023-09-11 19:08
This is broken in static exports, we need to update the dark mode to be based on local preferences rather than server side set cookies.

**Comment by rowanc1** [comment] 2024-03-11 13:25
Duplicate of #319

**Closed by rowanc1** 2024-03-11 13:25 UTC
